version: "3.9"

services:
  mcp:
    build: .
    command: ["python", "scripts/run_mcp.py"]
    mem_limit: "4g"
    cpus: "1"
    shm_size: "2gb"
    environment:
      PYTHONUNBUFFERED: "1"
  jsonschema:
    build: .
    command: ["python", "scripts/run_jsonschema.py"]
    mem_limit: "4g"
    cpus: "1"
    shm_size: "2gb"
    environment:
      PYTHONUNBUFFERED: "1"
